# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# the keys in this file are documented in
#   https://wiki.mozilla.org/ReleaseEngineering/PuppetAgain#Secrets
# if you add a new key here, add it to the wiki as well!
class config::secrets {
    $root_pw_hash = extlookup("root_pw_hash")
    $root_pw_pbkdf2 = extlookup("root_pw_pbkdf2")
    $root_pw_pbkdf2_salt = extlookup("root_pw_pbkdf2_salt")
    $root_pw_pbkdf2_iterations = extlookup("root_pw_pbkdf2_iterations")
    $builder_pw_hash = extlookup("builder_pw_hash")
    $builder_pw_pbkdf2 = extlookup("builder_pw_pbkdf2")
    $builder_pw_pbkdf2_salt = extlookup("builder_pw_pbkdf2_salt")
    $builder_pw_pbkdf2_iterations = extlookup("builder_pw_pbkdf2_iterations")
    $builder_pw_kcpassword_base64 = extlookup("builder_pw_kcpassword_base64")
    $builder_pw_vnc_base64 = extlookup("builder_pw_vnc_base64")
    $mozpool_inventory_url = extlookup("mozpool_inventory_url")
    $mozpool_inventory_username = extlookup("mozpool_inventory_username")
    $mozpool_inventory_password = extlookup("mozpool_inventory_password")
    $mozpool_db_hostname = extlookup("mozpool_db_hostname")
    $mozpool_db_username = extlookup("mozpool_db_username")
    $mozpool_db_password = extlookup("mozpool_db_password")
    $mozpool_db_database = extlookup("mozpool_db_database")
    $mozpool_staging_db_hostname = extlookup("mozpool_staging_db_hostname")
    $mozpool_staging_db_username = extlookup("mozpool_staging_db_username")
    $mozpool_staging_db_password = extlookup("mozpool_staging_db_password")
    $mozpool_staging_db_database = extlookup("mozpool_staging_db_database")
    $buildbot_statusdb_username = extlookup("buildbot_statusdb_username")
    $buildbot_statusdb_hostname = extlookup("buildbot_statusdb_hostname")
    $buildbot_statusdb_password = extlookup("buildbot_statusdb_password")
    $buildbot_statusdb_database = extlookup("buildbot_statusdb_database")
    $buildbot_schedulerdb_username = extlookup("buildbot_schedulerdb_username")
    $buildbot_schedulerdb_hostname = extlookup("buildbot_schedulerdb_hostname")
    $buildbot_schedulerdb_password = extlookup("buildbot_schedulerdb_password")
    $buildbot_schedulerdb_database = extlookup("buildbot_schedulerdb_database")
    $pulse_exchange = extlookup("pulse_exchange")
    $pulse_password = extlookup("pulse_password")
    $pulse_username = extlookup("pulse_username")
    $buildmaster_secrets = extlookup("buildmaster_secrets")
    $tuxedoUsername = extlookup("tuxedo_user")
    $tuxedoPassword = extlookup("tuxedo_password")
    $balrog_username = extlookup("balrog_username")
    $balrog_password = extlookup("balrog_password")
    $master_json = extlookup("master_json")
    $buildbot_tools_hg_repo = extlookup("buildbot_tools_hg_repo")
    $buildbot_configs_hg_repo = extlookup("buildbot_configs_hg_repo")
    $buildbot_mail_to = extlookup("buildbot_mail_to")
}
